@startuml
class VehicleRepository {
    + VehicleRepository(rentACarDbContext:RentACarDbContext)
    + <<async>> AddVehicle(vehicle:Vehicle) : Task
    + <<async>> UpdateVehicle(vehicle:Vehicle) : Task<Vehicle>
    + <<async>> RemoveVehicle(id:Guid) : Task
    + GetByVehicleIdWithAllData(vehicleId:Guid) : Task<Vehicle>
    + GetAllVehicles() : Task<IEnumerable<Vehicle>>
    + GetAllVehiclesWithAllData() : Task<IEnumerable<Vehicle>>
    + <<async>> GetVehicleById(id:Guid) : Task<Vehicle>
    + GetVehiclesFiltered(condition:Expression<Func<Vehicle, bool>>) : Task<IEnumerable<Vehicle>>
}
IVehicleRepository <|-- VehicleRepository
@enduml
