@startuml
class IncidentsController {
    + IncidentsController(incidentService:IIncidentService)
    + <<async>> AddIncident(incident:Incident) : Task<ActionResult<Incident>>
    + GetAllIncidents() : ActionResult<IEnumerable<Incident>>
    + <<async>> GetIncidentById(incidentId:Guid) : Task<ActionResult<Incident>>
    + <<async>> DeleteIncidentById(incidentId:Guid) : Task<IActionResult>
    + <<async>> UpdateIncident(incident:Incident) : Task<ActionResult<Incident>>
}
ControllerBase <|-- IncidentsController
@enduml
