ALTER TABLE "Client" ADD CONSTRAINT "PK_Client" PRIMARY KEY("Id");
ALTER TABLE "Vehicle" ADD CONSTRAINT "PK_Vehicle" PRIMARY KEY("Id");
ALTER TABLE "Incidents" ADD CONSTRAINT "PK_Incidents" PRIMARY KEY("Id");
ALTER TABLE "Incidents" ADD CONSTRAINT "FK_Incidents_VehicleId" FOREIGN KEY("VehicleId") REFERENCES "Vehicle"("Id");
ALTER TABLE "VehicleRent" ADD CONSTRAINT "PK_VehicleRent" PRIMARY KEY ("Id");
ALTER TABLE "VehicleRent" ADD CONSTRAINT "FK_VehicleRent_ClientId" FOREIGN KEY("ClientId") REFERENCES "Client"("Id");
ALTER TABLE "VehicleRent" ADD CONSTRAINT "FK_VehicleRent_VehicleId" FOREIGN KEY("VehicleId") REFERENCES "Vehicle"("Id");
CREATE INDEX "IX_VehicleRent_ClientId" on "VehicleRent"("ClientId");
CREATE INDEX "IX_VehicleRent_VehicleId" on "VehicleRent"("VehicleId");
CREATE INDEX "IX_Incidents_VehicleId" on "Incidents"("Id");
