counties = ["Arad", "Arges", "Bacau", "Bihor", "Bistrita-Nasaud", "Botosani", "Braila", "Brasov", "Buzau", "Calarasi", "Caras-Severin", "Cluj", "Constanta", "Covasna", "Dambovita", "Dolj", "Galati", "Giurgiu", "Gorj", "Harghita", "Hunedoara", "Ialomita", "Iasi", "Ilfov", "Maramures", "Mehedinti", "Mures", "Neamt", "Olt", "Prahova", "Salaj", "Sibiu", "Suceava", "Teleorman", "Timis", "Tulcea", "Valcea", "Vaslui", "Vrancea"]
counties_car_plate = ["AR",
                      "AG",
                      "BC",
                      "BH",
                      "BN",
                      "BT",
                      "BR",
                      "BV",
                      "BZ",
                      "CL",
                      "CS",
                      "CJ",
                      "CT",
                      "CV",
                      "DB",
                      "DJ",
                      "GL",
                      "GR",
                      "GJ",
                      "HR",
                      "HD",
                      "IL",
                      "IS",
                      "IF",
                      "MM",
                      "MH",
                      "MS",
                      "NT",
                      "OT",
                      "PH",
                      "SJ",
                      "SM",
                      "SB",
                      "SV",
                      "TR",
                      "TM",
                      "TL",
                      "VL",
                      "VS",
                      "VN"]

car_brands = ["Bmw","Audi","Mercedes","Dacia","Renault"]

cities= ["Alba",
	"Arad",
	"Piteşti",
	"Bacău",
	"Oradea",
	"Bistriţa",
	"Botoşani",
	"Brăila",
	"Braşov",
	"Buzău",
	"Călăraşi",
	"Reşiţa",
	"Cluj-Napoca",
	"Constanţa",
	"Sfântu",
	"Târgovişte",
	"Craiova",
	"Galaţi",
	"Giurgiu",
	"Târgu-Mures",
	"Miercurea Ciuc",
	"Deva",
	"Slobozia",
	"Iaşi",
	"Baia Mare",
	"Drobeta-Turnu Severin",
	"Târgu",
	"Piatra",
	"Slatina",
	"Ploieşti",
	"Zalău",
    "Satu-Mare",
	"Sibiu",
	"Suceava",
	"Alexandria",
	"Timişoara",
	"Tulcea",
	"Râmnicu",
	"Vaslui",
	"Focşani"
]

descriptions = ["The car hit a deer", "Driver felt asleep while driving during night", "Driver was staying on the phone and hit a car in the buttom"]

bios = ["Borned in 1979 in Zalau", "Being mechanic my entire life","Nurse here"]