ALTER TABLE "Client" DROP CONSTRAINT IF EXISTS "PK_Client" CASCADE;
ALTER TABLE "Vehicle" DROP CONSTRAINT IF EXISTS "PK_Vehicle" CASCADE;
 ALTER TABLE "VehicleRent" DROP CONSTRAINT IF EXISTS "PK_VehicleRent" Cascade;
ALTER TABLE "VehicleRent" DROP CONSTRAINT IF EXISTS "FK_VehicleRent_ClientId" Cascade;
ALTER TABLE "VehicleRent" DROP CONSTRAINT IF EXISTS "FK_VehicleRent_VehicleId" Cascade;
DROP INDEX IF EXISTS "IX_VehicleRent_VehicleId";
DROP INDEX IF EXISTS "IX_VehicleRent_ClientId";
