@startuml
!include ./Program.puml
!include ./Repository/VehicleRepository.puml
!include ./Repository/VehicleRentRepository.puml
!include ./Repository/IncidentRepository.puml
!include ./Repository/ClientRepository.puml
!include ./Migrations/20230313151400_ChangeToListOfVehicles.Designer.puml
!include ./Migrations/20230312185457_ClientMigration.Designer.puml
!include ./Migrations/20230312205139_AddedFabricationDate.puml
!include ./Migrations/20230318111517_AddedVehicleRentModel.Designer.puml
!include ./Migrations/20230312205139_AddedFabricationDate.Designer.puml
!include ./Migrations/20230318111517_AddedVehicleRentModel.puml
!include ./Migrations/RentACarDbContextModelSnapshot.puml
!include ./Migrations/20230312185457_ClientMigration.puml
!include ./Migrations/20230312174444_AddedEngineCapacityFieldInVehicleModel.puml
!include ./Migrations/20230312115148_InitializeDatabase.puml
!include ./Migrations/20230312204728_DeletedFabricationDate.puml
!include ./Migrations/20230313151400_ChangeToListOfVehicles.puml
!include ./Migrations/20230312115148_InitializeDatabase.Designer.puml
!include ./Migrations/20230312204728_DeletedFabricationDate.Designer.puml
!include ./Migrations/20230312174444_AddedEngineCapacityFieldInVehicleModel.Designer.puml
!include ./Service/VehicleRentService.puml
!include ./Service/VehicleService.puml
!include ./Service/IncidentService.puml
!include ./Service/ClientService.puml
!include ./Controller/IncidentsController.puml
!include ./Controller/ClientController.puml
!include ./Controller/VehicleController.puml
!include ./Controller/VehicleRentController.puml
!include ./Model/Vehicle.puml
!include ./Model/Incident.puml
!include ./Model/Client.puml
!include ./Model/VehicleRent.puml
!include ./Exceptions/RepositoryException.puml
!include ./DatabaseContext/RentACarDbContext.puml
!include ./Repository/Interfaces/IClientRepository.puml
!include ./Repository/Interfaces/IIncidentsRepository.puml
!include ./Repository/Interfaces/IVehicleRentRepository.puml
!include ./Repository/Interfaces/IVehicleRepository.puml
!include ./Service/Interfaces/IClientService.puml
!include ./Service/Interfaces/IVehicleService.puml
!include ./Service/Interfaces/IVehicleRentService.puml
!include ./Service/Interfaces/IIncidentService.puml
!include ./Model/DTO/VehicleDTO.puml
!include ./obj/Debug/net60/mpp1.GlobalUsings.g.puml
!include ./obj/Debug/net60/mpp1.AssemblyInfo.puml
!include ./obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./obj/Debug/net60/mpp1.MvcApplicationPartsAssemblyInfo.puml
@enduml
