@startuml
class VehicleController {
    + VehicleController(vehicleService:IVehicleService)
    + <<async>> AddVehicle(vehicle:Vehicle) : Task<ActionResult<Vehicle>>
    + GetAllVehicles() : ActionResult<IEnumerable<Vehicle>>
    + <<async>> GetVehicleById(vehicleId:Guid) : Task<ActionResult<Vehicle>>
    + <<async>> GetVehicleWithAllData(vehicleId:Guid) : Task<ActionResult<Vehicle>>
    + <<async>> DeleteVehicle(vehicleId:Guid) : Task<ActionResult>
    + <<async>> UpdateVehicle(vehicle:Vehicle) : Task<ActionResult<Vehicle>>
    + <<async>> GetVehiclesWithCapacityGreater(capacity:int) : Task<ActionResult<IEnumerable<Vehicle>>>
    + GetAllVehiclesWithAllData() : ActionResult<IEnumerable<Vehicle>>
    + <<async>> GetVehiclesByNumberOfIncidents() : Task<ActionResult<IEnumerable<VehicleDTO>>>
}
ControllerBase <|-- VehicleController
@enduml
