@startuml
class ClientController {
    + ClientController(clientService:IClientService)
    + <<async>> AddClient(client:Client) : Task<ActionResult<Client>>
    + <<async>> DeleteClient(clientId:Guid) : Task<IActionResult>
    + <<async>> GetClientById(clientId:Guid) : Task<ActionResult<Client>>
    + <<async>> GetAllClients() : Task<ActionResult<IEnumerable<Client>>>
    + <<async>> UpdateClient(client:Client) : Task<ActionResult<Client>>
}
ControllerBase <|-- ClientController
@enduml
