@startuml
class VehicleRent {
    + <<virtual>> Vehicle : Vehicle? <<get>> <<set>>
    + <<virtual>> Client : Client? <<get>> <<set>>
    + TotalCost : int <<get>> <<set>>
    + Comments : string? <<get>> <<set>>
}
VehicleRent --> "Id" Guid
VehicleRent --> "VehicleId" Guid
VehicleRent --> "ClientId" Guid
VehicleRent --> "StartDate" DateTime
VehicleRent --> "EndDate" DateTime
@enduml
