@startuml
class ClientService {
    + ClientService(clientRepository:IClientRepository)
    + <<async>> AddClient(client:Client) : Task
    + <<async>> RemoveClient(id:Guid) : Task
    + <<async>> UpdateClient(client:Client) : Task<Client>
    + GetAllClients() : Task<IEnumerable<Client>>
    + <<async>> GetClientById(id:Guid) : Task<Client>
}
IClientService <|-- ClientService
@enduml
