@startuml
interface IClientService {
    + AddClient(client:Client) : Task
    + RemoveClient(id:Guid) : Task
    + UpdateClient(client:Client) : Task<Client>
    + GetAllClients() : Task<IEnumerable<Client>>
    + GetClientById(id:Guid) : Task<Client>
}
@enduml
